spring.application.name=fightfitapi

spring.datasource.url = jdbc:postgresql://localhost:5432/fight-fit
spring.datasource.username = postgres
spring.datasource.password = admin
spring.jpa.hibernate.ddl-auto = update

spring.jpa.properties.hibernate.jdbc.lo.non_contextual_creation = true
spring.jpa.show-sql = true
